# Generated by Django 4.2.20 on 2025-03-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
